export const Types = {
    SELECT_RECORD: "SELECT_RECORD",
    SELECT_RECORDS: "SELECT_RECORDS",
    SELECT_SUCCESS: "SELECT_SUCCESS",
    SELECT_FAILURE: "SELECT_FAILURE",
    INSERT_RECORD: "INSERT_RECORD",
    UPDATE_RECORD: "UPDATE_RECORD",
    DELETE_RECORD: "DELETE_RECORD",
    STORE_DATA:"STORE_DATA"
  };
  